version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:6.20
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: moelcrow@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"  
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  image_downloader:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: image_downloader
      restart: unless-stopped
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        GOOGLE_API_KEY: ${GOOGLE_API_KEY}
        GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}
        MAX_IMAGE_SIZE: ${MAX_IMAGE_SIZE}  
      depends_on:
        - postgres
volumes:
  postgres_data:
  pgadmin_data:
